services:
  - type: web
    name: content-generator-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
