"""Add response_time to Analytics

Revision ID: 280230be9923
Revises: 2a2745b017a3
Create Date: 2025-07-29 18:38:48.894963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280230be9923'
down_revision: Union[str, Sequence[str], None] = '2a2745b017a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('response_time', sa.Float(), nullable=True))
    op.drop_column('generated_content', 'response_time_ms')
    op.drop_column('prompts', 'effectiveness_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('effectiveness_score', sa.FLOAT(), nullable=True))
    op.add_column('generated_content', sa.Column('response_time_ms', sa.FLOAT(), nullable=True))
    op.drop_column('analytics', 'response_time')
    # ### end Alembic commands ###
