"""Add prompt_effectiveness to Analytics

Revision ID: 7743eff2aaa9
Revises: 280230be9923
Create Date: 2025-07-29 18:42:09.297008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7743eff2aaa9'
down_revision: Union[str, Sequence[str], None] = '280230be9923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('prompt_effectiveness', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'prompt_effectiveness')
    # ### end Alembic commands ###
