"""Add engagement_score to Analytics

Revision ID: ecf1d6488742
Revises: 7743eff2aaa9
Create Date: 2025-07-29 18:48:39.053351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf1d6488742'
down_revision: Union[str, Sequence[str], None] = '7743eff2aaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('engagement_score', sa.Float(), nullable=True))
    op.drop_column('analytics', 'user_engagement_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('user_engagement_score', sa.FLOAT(), nullable=True))
    op.drop_column('analytics', 'engagement_score')
    # ### end Alembic commands ###
